# Generated by Django 4.2.2 on 2023-07-01 18:50

import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bunny', 'Bunny'), ('parrot', 'Parrot'), ('fish', 'Fish'), ('other', 'Other')], max_length=6)),
                ('DoB', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PetPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoFile', models.ImageField(upload_to='', validators=[
                    common.validators.ValidateFileMaxSizeInMb(max_size=5)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('tagged_pets', models.ManyToManyField(to='app.pet')),
            ],
        ),
    ]
